import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:practice_two/model/data.dart';
import 'package:practice_two/providers/screens_provider.dart';

class Favourite_Screen extends ConsumerWidget {
  const Favourite_Screen({super.key});

  @override
  Widget build(BuildContext context,WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(title: Text('Selected Iteam'),
      
      ),
      body: Center(
      child: Consumer(
        builder: (context, ref, child) {
          Photo state = ref.watch(dataprovider);
          if (state is loadingstate)
            return Center(
              child: CircularProgressIndicator(),
            );
          if (state is errorstate)
            return Center(
              child: Text(state.message),
            );
          if (state is loadedstate) {
            return ListView.builder(
              itemCount: state.photos.length,
              itemBuilder: (context, index) {
                Autogenerated photo = state.photos[index];
                return Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: ListTile(
                    minVerticalPadding: 10,
                    leading: CircleAvatar(
                      child: Image(image: NetworkImage(photo.url.toString())),
                    ),
                    title: Text(photo.title.toString()),
                    trailing: IconButton(
                      onPressed: () {
                      
                        Navigator.of(context).push(MaterialPageRoute(
                            builder: (context) => Favourite_Screen()));
                      },
                      
                      icon: Icon(
                        Icons.favorite_border,
                        size: 20,
                      ),
                    ),
                  ),
                );
              },
            );
          }
          return Text('nothing');
        },
      ),
    ),
    );
  }
}
