import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:practice_two/model/data.dart';



class httpRequest {
  final baseurl = 'https://jsonplaceholder.typicode.com';
  final endpoint = '/photos';

  Future<List<Autogenerated>> getpost() async {
    List<Autogenerated> photos = [];
    try {
      Uri photouri = Uri.parse('$baseurl$endpoint');
      http.Response response = await http.get(photouri);
      if (response.statusCode == 200) {
        List<dynamic> photolist = jsonDecode(response.body);
        photolist.forEach((iteams) {
          Autogenerated data = Autogenerated.fromJson(iteams);
          photos.add(data);
        });
      }
    } catch (e) {
      print(e.toString());
    }
    return photos;
  }
}
